"""Constants for name normalization and parsing."""

# Generational suffixes that should remain part of the standardized name
GENERATIONAL_SUFFIXES = {
    "jr",
    "sr",
    "ii",
    "iii",
    "iv",
    "v",
    "vi",
    "vii",
    "viii",
    "ix",
    "x",
}

# Professional/credential suffixes that should be stripped from standardized names
CREDENTIAL_SUFFIXES = {
    "esq",
    "esquire",
    "phd",
    "md",
    "dds",
    "dvm",
    "jd",
    "ma",
    "ms",
    "ba",
    "bs",
    "mba",
    "mfa",
    "mpp",
    "mph",
    "rn",
    "cpa",
    "cfa",
    "pe",
}

# US suffixes that should be recognized and extracted
US_SUFFIXES = GENERATIONAL_SUFFIXES | CREDENTIAL_SUFFIXES

# Indicators that a string is likely an organization/company rather than a person
CORPORATE_TERMS = {
    "inc",
    "inc.",
    "incorporated",
    "llc",
    "l.l.c.",
    "ltd",
    "l.t.d.",
    "limited",
    "corp",
    "corporation",
    "company",
    "co",
    "co.",
    "plc",
    "gmbh",
    "ag",
    "sa",
    "s.a.",
    "sarl",
    "bv",
    "nv",
    "pte",
    "pty",
    "llp",
    "l.l.p.",
    "lp",
    "l.p.",
    "pc",
    "p.c.",
    "pllc",
    "trust",
    "estate",
    "foundation",
    "ministries",
    "church",
    "university",
    "college",
    "credit union",
    "bank",
}

# Department/office phrases that should be treated as non-person names
NON_PERSON_PHRASES = {
    "human resources",
    "information desk",
    "information center",
    "general services",
    "general services administration",
    "general services department",
    "customer service",
    "service center",
    "service desk",
    "training room",
    "call center",
    "information technology",
    "finance department",
    "payroll",
    "accounts payable",
    "accounts receivable",
    "public works",
    "city hall",
    "city of",
    "board of commissioners",
    "board of education",
    "board of supervisors",
    "board of trustees",
    "commissioners",
    "the library",
    "library",
    "help support",
    "current resident",
    "postal customer",
    "system administrator",
    "system admin",
    "administrator",
    "municipal building",
    "administration",
}

# Roman numeral suffixes that should be uppercased in display
ROMAN_NUMERALS = {
    "ii": "II",
    "iii": "III",
    "iv": "IV",
    "v": "V",
    "vi": "VI",
    "vii": "VII",
    "viii": "VIII",
    "ix": "IX",
    "x": "X",
}

# Title prefixes to strip
TITLE_PREFIXES = {
    "mr",
    "mrs",
    "ms",
    "miss",
    "dr",
    "prof",
    "professor",
    "sir",
    "dame",
    "hon",
    "honorable",
    "honourable",
    "admiral",
    "rev",
    "reverend",
    "pastor",
    "imam",
    "rabbi",
    "father",
    "sister",
    "brother",
    "ofc",
    "officer",
    "sgt",
    "sergeant",
    "cpt",
    "capt",
    "captain",
    "lt",
    "lieutenant",
    "det",
    "detective",
    "chief",
    "deputy",
    "gov",
    "governor",
    "mayor",
    "sen",
    "senator",
    "rep",
    "interim",
    "judge",
    "justice",
    "amb",
    "ambassador",
}

# Placeholder values that should be treated as empty/unknown
PLACEHOLDER_NAMES = {
    "unknown",
    "tbd",
    "n/a",
    "na",
    "n\\a",
    "staff",
    "occupant",
    "none",
    "anonymous",
    "anon",
    "test",
    "tester",
    "testing",
    "demo",
    "sample",
    "placeholder",
    "temp",
    "user",
    "guest",
    "example",
    "candidate",
}
