"""Constants for title normalization."""

STOPWORDS = {
    "of",
    "and",
    "in",
    "on",
    "at",
    "for",
    "the",
    "per",
    "by",
    "to",
    "a",
}

TITLE_ABBREVIATIONS = {
    "dept": "Department",
    "maint": "Maintenance",
    "mgr": "Manager",
    "mgmt": "Management",
    "asst": "Assistant",
    "assoc": "Associate",
    "coord": "Coordinator",
    "spec": "Specialist",
    "sr": "Senior",
    "jr": "Junior",
    "vp": "Vice President",
    "avp": "Assistant Vice President",
    "svp": "Senior Vice President",
    "evp": "Executive Vice President",
    "ceo": "Chief Executive Officer",
    "coo": "Chief Operating Officer",
    "cfo": "Chief Financial Officer",
    "cio": "Chief Information Officer",
    "cto": "Chief Technology Officer",
    "cmo": "Chief Marketing Officer",
    "cpo": "Chief Product Officer",
    "cso": "Chief Security Officer",
    "cao": "Chief Academic Officer",
    "cro": "Chief Risk Officer",
    "cco": "Chief Compliance Officer",
    "ciso": "Chief Information Security Officer",
    "cdo": "Chief Data Officer",
    "chro": "Chief Human Resources Officer",
    "sgt": "Sergeant",
    "lt": "Lieutenant",
    "cpt": "Captain",
    "ofc": "Officer",
    "admin": "Administrator",
    "supt": "Superintendent",
    "supv": "Supervisor",
    "sec": "Secretary",
    "gm": "General Manager",
    "pm": "Project Manager",
    "prgm": "Program",
    "prog": "Program",
    "eng": "Engineer",
    "engr": "Engineer",
    "dev": "Developer",
    "devops": "DevOps",
    "qa": "Quality Assurance",
    "tech": "Technician",
    "cust": "Customer",
    "svc": "Service",
    "ops": "Operations",
    "fin": "Finance",
    "acct": "Accounting",
    "mktg": "Marketing",
    "pr": "Public Relations",
    "hr": "Human Resources",
    "it": "Information Technology",
    "ux": "User Experience",
    "ui": "User Interface",
}

# Abbreviations that should be preserved and not expanded
PRESERVE_ABBREVIATIONS = {"dir"}
